export const API_KEY = '8322b5e1fca144759bb100026241801';

export const weatherImages = {
  'Partly cloudy': require('../assets/images/partlycloudy.png'),
  'Moderate rain': require('../assets/images/moderaterain.png'),
  'Patchy rain possible': require('../assets/images/moderaterain.png'),
  Sunny: require('../assets/images/sun.png'),
  Clear: require('../assets/images/sun.png'),
  Overcast: require('../assets/images/cloud.png'),
  Cloudy: require('../assets/images/cloud.png'),
  'Light rain': require('../assets/images/moderaterain.png'),
  'Light rain shower': require('../assets/images/moderaterain.png'),
  'Modarate rain at times': require('../assets/images/moderaterain.png'),
  'Heavy rain': require('../assets/images/heavyrain.png'),
  'Heavy rain at times': require('../assets/images/heavyrain.png'),
  'Moderate or heavy freezing rain': require('../assets/images/heavyrain.png'),
  'Moderate or heavy freezing rain': require('../assets/images/heavyrain.png'),
  'Moderate or heavy rain with thunder': require('../assets/images/heavyrain.png'),
  'Moderate or heavy snow showers': require('../assets/images/snow.png'),
  'Moderate snow': require('../assets/images/snow.png'),
  'Patchy light snow': require('../assets/images/snow.png'),
  'Light snow': require('../assets/images/snow.png'),
  'Light freezing snow': require('../assets/images/snow.png'),
  'Freezing fog': require('../assets/images/snow.png'),
  'Light freezing rain': require('../assets/images/snow.png'),
  Mist: require('../assets/images/partlycloudy.png'),
  Other: require('../assets/images/moderaterain.png'),
};

export const weatherAnimations = {
  'Partly cloudy': require('../assets/animations/partlycloudy.json'),
  'Moderate rain': require('../assets/animations/moderaterain.json'),
  'Patchy rain possible': require('../assets/animations/moderaterain.json'),
  Sunny: require('../assets/animations/sun.json'),
  Clear: require('../assets/animations/sun.json'),
  Overcast: require('../assets/animations/cloud.json'),
  Cloudy: require('../assets/animations/cloud.json'),
  'Light rain': require('../assets/animations/moderaterain.json'),
  'Light rain shower': require('../assets/animations/moderaterain.json'),
  'Modarate rain at times': require('../assets/animations/moderaterain.json'),
  'Heavy rain': require('../assets/animations/heavyrain.json'),
  'Heavy rain at times': require('../assets/animations/heavyrain.json'),
  'Moderate or heavy freezing rain': require('../assets/animations/heavyrain.json'),
  'Moderate or heavy freezing rain': require('../assets/animations/heavyrain.json'),
  'Moderate or heavy rain with thunder': require('../assets/animations/heavyrain.json'),
  'Moderate or heavy snow showers': require('../assets/animations/snow.json'),
  'Moderate snow': require('../assets/animations/snow.json'),
  Mist: require('../assets/animations/partlycloudy.json'),
  'Patchy light snow': require('../assets/animations/lightSnow.json'),
  'Light snow': require('../assets/animations/lightSnow.json'),
  'Light freezing snow': require('../assets/animations/lightSnow.json'),
  'Light freezing rain': require('../assets/animations/lightSnow.json'),
  'Freezing fog': require('../assets/animations/snow.json'),
  'Freezing fog': require('../assets/animations/snow.json'),
  Other: require('../assets/animations/moderaterain.json'),
};
export const weatherAnimationsNight = {
  'Partly cloudy': require('../assets/animations/partlycloudy-night.json'),
  'Moderate rain': require('../assets/animations/moderaterain-night.json'),
  'Patchy rain possible': require('../assets/animations/moderaterain-night.json'),
  Sunny: require('../assets/animations/moon.json'),
  Clear: require('../assets/animations/moon.json'),
  Overcast: require('../assets/animations/cloud.json'),
  Cloudy: require('../assets/animations/cloud.json'),
  'Light rain': require('../assets/animations/moderaterain-night.json'),
  'Light rain shower': require('../assets/animations/moderaterain-night.json'),
  'Modarate rain at times': require('../assets/animations/moderaterain-night.json'),
  'Heavy rain': require('../assets/animations/moderaterain-night.json'),
  'Heavy rain at times': require('../assets/animations/moderaterain-night.json'),
  'Moderate or heavy freezing rain': require('../assets/animations/moderaterain-night.json'),
  'Moderate or heavy freezing rain': require('../assets/animations/moderaterain-night.json'),
  'Moderate or heavy rain with thunder': require('../assets/animations/moderaterain-night.json'),
  'Moderate or heavy snow showers': require('../assets/animations/snow.json'),
  'Moderate snow': require('../assets/animations/snow.json'),
  Mist: require('../assets/animations/partlycloudy-night.json'),
  'Patchy light snow': require('../assets/animations/snow.json'),
  'Light snow': require('../assets/animations/snow.json'),
  'Light freezing snow': require('../assets/animations/snow.json'),
  'Light freezing rain': require('../assets/animations/snow.json'),
  'Freezing fog': require('../assets/animations/snow.json'),
  'Freezing fog': require('../assets/animations/snow.json'),
  Other: require('../assets/animations/moderaterain-night.json'),
};
